src/test/java/org/alfresco/repo/content/transform/HtmlParserContentTransformerTest.java
test failing when run locally on systems other than Linux
=> REPO-2872: fix HtmlParserContentTransformerTest.testEncodingHandling

src/main/java/org/alfresco/repo/node/UndeletableAspect.java, src/test/java/org/alfresco/repo/coci/CheckOutCheckInServiceImplTest.java
Added a policy implementation to the UndeletableAspect class so that
the aspect is not copied to other nodes.
This solves the problem where a document has the aspect added to it by
Cloud sync (for example) and is then checked-out, but may never be
checked in again (or editing cancelled) as the working copy included
the sys:undeletable aspect.
=> MNT-18546: exclude the undeletable aspect from node copies (REPO-2876)

src/main/java/org/alfresco/opencmis/CMISConnector.java, src/test/java/org/alfresco/opencmis/CMISTest.java
Fixes CMIS sys:* aspect update behaviour — clients must not manipulate sys aspects via CMIS
This follows on from (and depends upon) the fix for MNT-18340 which has already been merged into develop.
Since this is an API-breaking change, it will go into 6.0+ only (merge to develop with no backport)
*Apologies for the spurious end-of-line changes* — I've now worked out why this is happening. I have my IDE set to remove trailing whitespace upon save, so that I don't save empty lines with the auto-indent left hanging. Unfortunately it seems that a lot of existing code has trailing space that is being manipulated by this feature, so I'll disable it now.
=> REPO-2926: CMIS update now ignores aspects in the sys namespace (MNT-18340)

src/main/resources/alfresco/core-services-context.xml
Now that we have "decomposed" various parts of the mega-monolith repository
into smaller projects such as alfresco-remote-api, we need a mechanism for
adding new system properties within the project that requires them.
For example, to add a new boolean/toggle for the WWW-Authenticate behaviour
in the remote API project, we don't want that setting to go in
alfresco-repository - we want it to live in alfresco-remote-api. So this
extra pattern (classpath*:alfresco/project.properties) is being added to
load these project specific properties.
=> REPO-2575: added property loader pattern for non-enterprise projects

src/main/resources/alfresco/public-services-security-context.xml, src/test/java/org/alfresco/repo/security/permissions/impl/PermissionServiceTest.java
The PermissionService had security config for two methods missing:
* hasReadPermission
* getAuthorisations
getAuthorisations was duplicated as ACL_DENY as it is a system only performance method.
=> REPO-3013 Fix security config for PermissionService

src/main/java/org/alfresco/repo/transfer/TransferVersionCheckerImpl.java, src/test/java/org/alfresco/AllUnitTestsSuite.java, src/test/java/org/alfresco/AppContext04TestSuite.java, src/test/java/org/alfresco/repo/transfer/TransferVersionCheckerImplTest.java
As FTR is now a separate project it is not feasible to check the minor version and edition during transfer.
Now only major version is checked (6 in this case).
=> REPO-3040 Make TransferVersionCheckerImpl less restrictive

src/main/java/org/alfresco/repo/quickshare/QuickShareServiceImpl.java
The metadata regarding a shared document must include the `cm:description` property.
This minor change needs releasing in the repository jar so that `alfresco-remote-api` may have its pom.xml updated to use the new version and so have the description property available in the quick share link REST API.
I would have added a test case, but there didn’t seem anything appropriate to add it to (and creating a whole test for a single property addition didn’t seem useful right now)
Of course there are REST API tests coming up that fail without this repo addition, so it is tested there.
Build:
https://bamboo.alfresco.com/bamboo/browse/PLAT-REP47
=> REPO-2828: add 'description' for shared link info

src/main/java/org/alfresco/repo/workflow/WorkflowDefinitionType.java, src/main/java/org/alfresco/repo/workflow/WorkflowDeployer.java, src/test/java/org/alfresco/repo/workflow/activiti/ActivitiWorkflowServiceIntegrationTest.java, src/test/resources/alfresco/workflow/test-security.bpmn20.xml
This fix stops a non-admin user from being able to create a content node, then turn it into a workflow and deploy it. It also tightens up the requirement that workflows deployed in this way are only accepted in the correct place.
=> REPO-3107/MNT-18764: workflow admin security bypass

src/main/java/org/alfresco/repo/security/authentication/AuthenticationServiceImpl.java, src/test/java/org/alfresco/repo/security/authentication/AuthenticationServiceImplTest.java
The protection respects the setting of user.name.caseSensitive (default is false).
=> REPO-3109: Brute force protection can be bypassed by changing username case

src/main/java/org/alfresco/repo/search/NodeServiceXPath.java
Fix for REPO-1886 / ALF-21822: create new list instead of using the old list. 
For some reason it seems that the retrieved list may be used in other operations, so instead of mutating this one to remove duplicates, a new list is created and returned without duplicates. Couldn't reproduce the issue using acp import as suggested in ALF-21822
=> REPO-1886 / ALF-21822: NodeServiceXPath: Unsupported operation list.clear()

src/test/java/org/alfresco/repo/jscript/ScriptNodeTest.java
ALF-21962: Webscripts - node.qnamePath incorrectly returns : for items without namespace prefix
=> REPO-3111: Community: ALF-21962: Webscripts - node.qnamePath incorrect

src/main/java/org/alfresco/repo/site/SiteServiceImpl.java, src/test/java/org/alfresco/repo/site/SiteServiceImplMoreTest.java
REPO-2811 / ALF-21924: "Internal Server Error" when listSites is invoked for users belonging to a deleted Site
- added a fix by not adding site / user pair to the membership list if the role is null
- added a Junit
=> ALF-21924: "Internal Server Error" when listSites is invoked for users belonging to a deleted Site

src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceImpl.java, src/test/java/org/alfresco/opencmis/CMISTest.java
Separete into different new transactions writing content from creatingObjectId for setContentStream()
Separate into different new transactions deleteing content from creatingObjectId for deleteContentStream()
Separate into different new transations appending content from creatingObjectId for appendContentStream()
Create JUnit CMISTest.testSetDeleteAppendContentStreamVersioning() testing that set/delete/apped calls return the new version.
=> REPO-2182 : Community: ALF-21852: setContentStream() returns the wrong document version when auto-versioning is turned on

src/main/java/org/alfresco/repo/site/SiteServiceImpl.java, src/test/java/org/alfresco/repo/site/SiteServiceImplTest.java
- Limited the ```/people/<username>/sites``` API (V0 and V1) to filter out private sites when querying for users other than currently authenticated one and site admins.
- Tests: changed most of the site names to unique values, to be able to rerun tests locally without cleaning the database.
=> REPO-3149 / MNT-19035 - Limit the /people/<username>/sites API

src/main/java/org/alfresco/repo/action/ParameterizedItemDefinitionImpl.java, src/test/java/org/alfresco/repo/action/ActionDefinitionImplTest.java, src/test/java/org/alfresco/repo/forms/processor/action/ActionFormProcessorTest.java, src/test/java/org/alfresco/repo/i18n/MessageServiceImplTest.java
REPO-2253: Community: ALF-21854 Action parameter lookup for "de_DE" falls back to "root" locale instead of "de"
This fixes the locale fallback problem for action definitions, such that if a parameter definition exists for German ("de") and the client asks for it with the locale Germany ("de-DE") then the labels will be returned in German, rather than English, even though there is no specific language bundle for the de-DE locale.
=> REPO-2253/ALF-21854 Fix action parameter locale lookup

src/main/java/org/alfresco/repo/security/authentication/AuthenticationServiceImpl.java, src/main/resources/alfresco/subsystems/Authentication/common-ldap-context.xml, src/main/resources/alfresco/subsystems/Authentication/external/external-authentication-context.xml, src/test/java/org/alfresco/repo/security/authentication/external/LocalAuthenticationServiceTest.java
ignore authentication protection for ext auth, and use the unsercure personService bean to be able to check if the system uses case sensitive usernames
=> REPO-3255: Service Pack: MNT-19181 and MNT-19129: Authentication regressions

pom.xml, src/test/java/org/alfresco/repo/imap/ImapMessageTest.java
- upgraded javax.mail to 1.6.1
- updated testEncodedFromToAddresses to reflect that starting javax.mail 1.5.6 the address is folded at linear whitespace so that each line is no longer than 76 characters, if possible
=> REPO-1292: Upgrade javax.mail if test failure is a false positive

pom.xml
I upgraded Rhino to **1.7.9**, which is the most recent release - https://github.com/mozilla/rhino/releases/tag/Rhino1_7_9_Release (March 15, 2018).
There isn't any diff file in the code, to identify what was patched in the version `1.7R4-alfresco-patched`, so I did a compare between the zip that is suppose to be the source zip for the patched version and the source for the 1.7R4 release, and the only difference I found was in `org.mozilla.javascript.ScriptRuntime.warnAboutNonJSObject`, where the actual logging of the warning is removed.
In the 1.7.9 version, this logging is based on the value of a flag and is omitted by default (https://github.com/mozilla/rhino/blob/Rhino1_7_9_Release/src/org/mozilla/javascript/ScriptRuntime.java#L4312), so no need to patch the latest version.
=> REPO-1323: Rhino upgrade to 1.7.9

pom.xml
Quartz uses c3p0 jdbc pool for it's distributed job storage since version 2.x
This commit will exclude c3p0 lib as distributed job storage is not used.
=> REPO-3447: Remove c3p0

pom.xml, src/main/java/org/alfresco/repo/lock/LockServiceImpl.java, src/main/java/org/alfresco/repo/lock/LockServicePolicies.java, src/test/java/org/alfresco/repo/lock/LockServiceImplTest.java
- New policies for lock/unlock events
- Invoke the beforeUnlock policy in LockServiceImpl#unlock()
- Changed alfresco-events version to 1.2.10 in pom.xml
- Test for the new policies
=> APPSREPO-423 : Create new policies on repository side

pom.xml, src/main/resources/alfresco/repository.properties
CSRF filter is now configured by these props:
csrf.filter.referer=
csrf.filter.referer.always=false
csrf.filter.origin=
csrf.filter.origin.always=false
Referer and origin here is a regexp and should look like:
http://mydomain:80/*.
=> REPO-3465  Add CSRF filter config

src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
I changed the JOIN to LEFT JOIN to the `alf_store` table, in the statement that gets eventually executed when the groups api is called.
There have been other issues in the past related to the fact that the inner join slows down the query and the left join performs better in practice (some linked in the MNT).
=> REPO-3625 / MNT-19701: Groups rest api call is very expensive on the DB CPU

src/main/java/org/alfresco/repo/descriptor/DescriptorStartupLog.java, src/main/resources/alfresco/messages/system-messages.properties
Added log message: "To extend the trial period visit: https://www.alfresco.com/platform/content-services-ecm/trial/docker"
=> REPO-3747 Trials: Changes to license generation and docs

src/main/java/org/alfresco/repo/security/authority/AuthorityDAOImpl.java, src/main/resources/alfresco/authority-services-context.xml, src/main/resources/alfresco/repository.properties
The hardcoded 100 max items limit was changed to a configurable parameter `authority.findAuthorityLimit` which now has a default of 10000.
This limit is applied to a query that is going in SearchService, therefore can go to Solr instead of database if Full Text Search queries are configured to use Solr instead of the database.
As the query returns all items and sorting and paging is done in remote-api in `GroupsImpl#getAuthoritiesInfo`, the execution can be slow on large datasets. Local tests showed about 6s to get results for a group of 10000 users.
=> REPO-3744 Make query limit configurable

src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
* The rendition service 2 now updates the lastThumbnailModification on the source node when the thumbnail is updated
=> REPO-3692: Fix thumbnail last modified logic

src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
- There was a check for the bootstrap marker missing in the if statement that initialized and created the activiti tables in the DB.
- Added more logging as the cluster boot up is much more frequent now with Kubernetes and docker, we need better logging so we can determine if there are problems, what went wrong
=> REPO-3808: Fix activiti table bootstrap in large cluster and add more logging

pom.xml, src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceImpl.java, src/test/java/org/alfresco/opencmis/CMISTest.java
- removed code that was made useless by previous code changes (see MNT-15338)
- added junit for the case when getAllVersions() is used with null objectId (Cmis WS binding)
=> REPO-3627 / MNT-19630: CMIS: Unable to call getAllVersions() if node is checked out and if binding type is WSDL

src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java, src/main/resources/alfresco/rendition-services2-context.xml, src/test/java/org/alfresco/repo/rendition2/LegacyLocalTransformServiceRegistryTest.java, src/test/java/org/alfresco/repo/rendition2/RenditionDefinitionTest.java, src/test/java/org/alfresco/transform/client/model/config/TransformServiceRegistryImplTest.java
The RemoteTransformClient was not sending the transform to the Transform Service because, the "pdf" rendition had an extra allowEnlargement option, which had been added in 6.1 EA3 as a way to force the conversion to use the ImageTransformationOptions sub class rather then TransformationOptions. While investigation this bug, it was found the type should have been SWFTransformationOptions, which had been incorrectly added in ACS 5.2
Green build: https://bamboo.alfresco.com/bamboo/browse/PLAT-REP263-UNIT-2
=> REPO-3972  doc to pdf is not sent to the Transform Service

src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java, src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceDeploymentFactoryBean.java, src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapper.java, src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml, src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapperTest.java, src/test/resources/alfresco-global.properties
* Set timeout to the http client used by keycloak to retrieve a public key
* Ensure that the user mapper does not throw exceptions
* IdentityServiceRemoteUserMapper should not attempt basic authentication
=> REPO-3876: Fix Remote User Mapper

pom.xml
- updated Gytheio to 0.9 OpenJDK11 compatible
Gytheio 0.9 [release notes](https://github.com/Alfresco/gytheio/releases/tag/v0.9).
With this release the Gytheio library is OpenJDK11 compatible.
Note: v0.9 is equivalent to v0.8 with the following specific changes
* [MM-764](https://issues.alfresco.com/jira/browse/MM-764) :  Build: MM / Gytheio updates for OpenJDK 11 support (build tests)
* [MM-665](https://issues.alfresco.com/jira/browse/MM-665) : Gytheio: Update to commons-io 2.6
* Update compile source/target from 1.8 to 11 (including build plan)
Changes included:
* setting `maven.compiler.source` & `maven.compiler.target` to 11, see [this line](https://github.com/Alfresco/gytheio/blob/9253edfa4fbd175cf9aefe1c31352af593d65666/pom.xml#L36)
* addition of `javax.xml.bind:jaxb-api:2.3.1`, see …
=> MM-769 : Release Gytheio 0.9 (OpenJDK 11 compatible)

pom.xml
As per @killerboot request we have reverted `maven.compiler.source` and `maven.compiler.target` back to `1.8` in the Gytheio library.
This meant another another release, therefor, here is Gytheio 0.9.1.
This was done in order to ensure backwards compatibility.
FYI
Previous 0.9 [pull request](https://github.com/Alfresco/alfresco-repository/pull/267).
Gytheio 0.9.1 [release notes](https://github.com/Alfresco/gytheio/releases/tag/v0.9.1).
=> MM-773 : Release Gytheio 0.9.1 (OpenJDK 11 compatible)

src/main/java/org/alfresco/util/ApplicationContextHelper.java
This class is mainly used as a utility in tests to cache ApplicationContext.
After upgrade to Spring 5 native annotations can be used instead.
=> Deprecate ApplicationContextHelper

src/main/java/org/alfresco/repo/virtual/template/SortConstraint.java, src/test/java/org/alfresco/repo/virtual/template/VirtualQueryImplTest.java
The PR contains: 
- a change in the SortConstraint class for using the prefixed attribute name (i.e. prefix:localname) instead of local name (the namespace was completely ignored) 
- the corresponding fix to the unit tests
The proposed solution doesn't include an integration test because at the moment we don't have the required infrastructure for setting up (through API) the required environment with the steps described in the issue.
=> [ MNT-19763 ] Sorting on smart folders using custom attributes fails

pom.xml, src/main/java/org/alfresco/repo/rendition/RenditionServiceImpl.java, src/main/java/org/alfresco/repo/rendition2/LegacyLocalTransformClient.java, src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java, src/main/java/org/alfresco/repo/rendition2/SwitchingTransformClient.java, src/main/java/org/alfresco/repo/rendition2/TransformClient.java, src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java, src/test/java/org/alfresco/repo/rendition2/LegacyLocalTransformClientIntegrationTest.java, src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java, src/test/java/org/alfresco/repo/thumbnail/ThumbnailServiceImplParameterTest.java
An exception was being thrown if there was no supported rendition. In the case where a rendition already existed, RenditionService2 should have removed the content and hashcode on the rendition node and updated the source nodes thumbnailLastModified value. This is what happens if there is a  transform failure when there is a rendition available.
=> REPO-4099 Change of mimetype to unsupported rendition hangs Share

pom.xml, src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java, src/test/java/org/alfresco/repo/rendition2/LegacyLocalTransformClientIntegrationTest.java
Only include URL and mimetype when working out the content hashCode as we don't want it to change if deleted.
=> REPO-4099 Change of mimetype to unsupported rendition hangs Share (#298)

src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication.properties
The default values for `realm` and `resource` have been changed in the 1.0 release of AIS. The DBP Charts currently need to overwrite these values. See
https://github.com/Alfresco/alfresco-dbp-deployment/blob/177e0fb57cd39d2db0c14572843310fac6ffafeb/charts/incubator/alfresco-dbp/values.yaml#L52
=> Update identity-service configuration to match AIS 1.0 defaults

src/main/java/org/alfresco/repo/jscript/app/UsernamePropertyDecorator.java
The source of the bug is a change in the `PersonServiceImpl.personExists` method which considers now built-in authorities (system, guest) as existing by default.
The System case was dealt with after checking on the person existence, so I switched between the two `ifs`. 
I checked for similar usages in the code and it doesn't seem to be any other left.
=> REPO-4132: After upgrade the repository is empty

src/test/java/org/alfresco/RepositoryStartStopTest.java
* The refreshing of our core application context does not work with Spring version greater than 5.1.0
* We don't need to test refreshing the core application context as that never happens, only the subsystem application contexts are refreshed
=> REPO-3962: Remove context refresh from testOpenCloseOpenCloseFull

src/main/java/org/alfresco/repo/search/impl/lucene/index/IndexInfo.java, src/main/java/org/alfresco/repo/transfer/HttpClientTransmitterImpl.java, src/test/java/org/alfresco/repo/content/AbstractWritableContentStoreTest.java, src/test/java/org/alfresco/repo/content/filestore/FileIOTest.java
- explicit cast for compatibility with covariant return type on JDK 9's ByteBuffer
=> REPO-4102: MNT-20213: Unable to run using Java 8

src/main/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClient.java, src/test/java/org/alfresco/AllUnitTestsSuite.java, src/test/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClientTest.java
* RM-6141: RM_support_for_the_Insight_Engine
Pass filter queries in SQL requests to the Insight Engine.
* SEARCH-1351 Add unit tests for SolrSQLHttpClient.
This involved changing the return type of postSolrQuery. The cast
taking place in this file did not make sense to me, since the two
types are not in the same type hierarchy. However it is obviously
working at the moment, so I have simply moved the location of the
cast. I couldn't find any references to the protected method anyway,
so it did not seem risky to update.
* SEARCH-1351 Add new unit test file to suite.
* SEARCH-1351 Remove unused test variables and fix logging.
(cherry picked from commit b2a25d29a374bba4e38ee90f0d4aa76506f3931d)
=> RM-6141: RM_support_for_the_Insight_Engine (#301)

src/main/java/org/alfresco/repo/copy/CopyServiceImpl.java
Changed implementation of map so that the insertion order is preserved, with this the onCopyComplete-Policy is called in the right order in case of an recursive copy.
The LinkedHashMap preserves the insertion order of the entries, so the Policy is called in the exact order of copy-operations.
I did not know how to extend CopyServiceImplTest for this, if anyone has an idea, let me know. Otherwise i would say that the change will have no effect to other components.
=> ALF-22056: onCopyComplete-Policy not called in order of copy-action

pom.xml, src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
adding a left join for alf_store targetStore, to improve the query time and the load on the DB server
=> REPO-4262: HotFix: MNT-20383: Associations query takes a long time to run and consumes a lot of CPU on the DB side

src/main/java/org/alfresco/repo/action/executer/MailActionExecuter.java, src/test/java/org/alfresco/repo/action/executer/AbstractMailActionExecuterTest.java
In order to get the correct rendering in Outlook, we need to update some of our HTML email templates to include a doctype at the start. However, this causes Alfresco to send them as Plain Text instead of HTML, because the logic in `MailActionExecutor` to decide if a `FTL` template rendered into HTML or Plain Text only considers the opening HTML tag, not a HTML Doctype declaration
The logic in the `isHTML` method needs to consider this too. In addition, unit testing is required for all of the HTML detection logic, including this new check.
Also raised as ALF-22073
=> Mail action executor better html detection

src/main/java/org/alfresco/repo/download/DownloadServiceImpl.java, src/main/java/org/alfresco/repo/download/DownloadStorage.java, src/main/java/org/alfresco/repo/download/DownloadsCleanupJob.java, src/main/java/org/alfresco/repo/node/SystemNodeUtils.java, src/main/java/org/alfresco/service/cmr/download/DownloadService.java, src/main/resources/alfresco/download-services-context.xml, src/main/resources/alfresco/repository.properties, src/test/java/org/alfresco/repo/download/DownloadServiceIntegrationTest.java
Modified the SystemNodeUtils to run as system when access to the "sys:download" folder is required. 
This will prevent other "sys:download" (with differnt GUID) to be created, as it was the case in the past for non admin users;
I also added code to the DownloadService and DownloadStorage classes to handle the deletion of the old download zip files that were not deleted by the DownloadsCleanupJob because of this bug.
I added support for batching for this deletion, since old repositories may potentially contain a lot of these old files that were not deleted for years.
=> REPO-4284: MNT-20212:  Download as Zip temp content never gets cleaned up by Download Cleaner

src/main/java/org/alfresco/repo/imap/ImapServiceImpl.java, src/test/java/org/alfresco/repo/imap/ImapServiceImplTest.java
* Added functionality to filter IMAP folders based on their component IDS
=> REPO-830: 6.0 Cleanup: Remove link between IMAP, Calendar and Data Lists

src/main/java/org/alfresco/repo/management/JmxDumpUtil.java, src/test/java/org/alfresco/repo/management/JmxDumpUtilTest.java
Added new methods to parse the InputArguments section of the JMXDump, in order to redact any instances of plain text passwords.
=> REPO-4305: jmx dump password redaction inconsistent

pom.xml, src/main/java/org/alfresco/filesys/repo/CIFSContentComparator.java
Updated `alfresco-data-model`, which depends on the patched tika -`1.21-20190624-alfresco-patched`.
`poi` library was updated to 4.0.1 to match the version in tika.
=> REPO-4366 / REPO-4458: Update Tika to 1.21-alfresco-patched

pom.xml
- Updated gytheio-messaging-camel to version 0.10 which brings a newer version of camel-jackson (2.24.0)
see https://github.com/Alfresco/gytheio/releases/tag/v0.10
=> REPO-4525 / MNT-2075: Multiple camel-jackson vulnerabilities

.travis.yml, pom.xml
There is a dependency in data-model that uses cxf-rt-frontend-jaxws, which is at version 3.3.2. However, in the repository dependency tree it uses version 3.0.12, and has been causing failures in acs-packaging All amps validation in the 6.0.N line (multiple asm libraries)
cglib is causing a multiple library error in acs-packagin (asm)
=> REPO-4504 upgrade cxf-rt-transports-http 6.0

.travis.yml, pom.xml
There is a dependency in data-model that uses cxf-rt-frontend-jaxws, which is at version 3.3.2. However, in the repository dependency tree it uses version 3.0.12, and has been causing failures in acs-packaging All amps validation in the 6.0.N line (multiple asm libraries). 
(cherry picked from commit 77509f085725e6fe700ba87863bdf7cf3ccd817e)
=> REPO-4504 upgrade cxf-rt-transports-http 6.1

pom.xml
Upgrade camel-jackson version (2.24.0) and exclude the dependency from gytheio.
=> REPO-4525: Upgrade camel-jackson version (2.24.0)

pom.xml
Those libs come from TIKA anyways.
=> Remove unused tagsoup and metadata-extractor libs

src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
Handled the case in which no QName is found for shard.key.
Avoid to throw exceptions and added log messages.
=> [SEARCH-1829]

src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
Change access modifier from private to protected for TransformationOptionsConverter#Setter interface and TransformationOptionsConverter#ifSet as TransformationOptionsConverter is required to be sub-classed by custom legacy Transformers.
=> Cannot subclass TransformationOptionsConverter

src/main/java/org/alfresco/repo/content/transform/AbstractContentTransformer2.java, src/main/java/org/alfresco/repo/content/transform/AbstractContentTransformerLimits.java, src/main/java/org/alfresco/repo/content/transform/AdminUiTransformerDebug.java, src/main/java/org/alfresco/repo/content/transform/FailoverContentTransformer.java, src/main/java/org/alfresco/repo/content/transform/LegacyTransformerDebug.java, src/main/java/org/alfresco/repo/content/transform/OOoContentTransformerHelper.java, src/main/java/org/alfresco/repo/content/transform/TransformerConfigDynamicTransformers.java, src/main/java/org/alfresco/repo/content/transform/TransformerConfigMBean.java, src/main/java/org/alfresco/repo/content/transform/TransformerConfigMBeanImpl.java, src/main/java/org/alfresco/repo/content/transform/TransformerDebug.java, src/main/java/org/alfresco/repo/content/transform/TransformerSelectorImpl.java, src/main/java/org/alfresco/repo/rendition2/ContentTransformServiceImpl.java, src/main/java/org/alfresco/repo/rendition2/LegacyTransformServiceRegistry.java, src/main/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClient.java, src/main/resources/alfresco/content-services-context.xml, src/test/java/org/alfresco/repo/content/transform/LegacyTransformerDebugTest.java, src/test/java/org/alfresco/repo/content/transform/TransformerConfigDynamicTransformersTest.java, src/test/java/org/alfresco/repo/content/transform/TransformerConfigMBeanImplTest.java, src/test/java/org/alfresco/repo/content/transform/TransformerConfigTestSuite.java
- Re factored TransformerDebug so the Legacy transform code has been extracted into
LegacyTransformerDebug and code used by the Admin console's Test Transform that is
not being deprecated has been extracted into AdminUiTransformerDebug
- Removed a few tests for a method that no longer supports specifying a transform name.
- All other changes are to handle the fact that the transformerDebug bean is now a
LegacyTransformerDebug class and methods have been moved to sub classes.
=> REPO-4791 Use Local transforms where Legacy transforms are called.

pom.xml
=> REPO-4800 - Remove library oro:oro from alfresco-repository project

pom.xml
=> REPO-4802 - Remove library cglib:cglib from alfresco-repository project

pom.xml, src/main/java/lib3party/org/apache/chemistry/opencmis/server/support/wrapper/AbstractCmisServiceWrapper.java, src/main/java/lib3party/org/apache/chemistry/opencmis/server/support/wrapper/CallContextAwareCmisService.java, src/main/java/lib3party/org/apache/chemistry/opencmis/server/support/wrapper/ConformanceCmisServiceWrapper.java, src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceFactory.java, src/main/java/org/alfresco/opencmis/AlfrescoLocalCmisServiceFactory.java
=> REPO-4870 - Remove library org.apache.chemistry.opencmis:chemistry-opencmis-server-support from alfresco-repository project

pom.xml
=> REPO-4883 - Remove library xpp3:xpp3 from alfresco-data-model project

pom.xml
=> REPO-4886 - Remove library org.mybatis:mybatis from alfresco-core

src/main/java/org/alfresco/repo/policy/BehaviourFilter.java, src/main/java/org/alfresco/repo/policy/BehaviourFilterImpl.java, src/main/java/org/alfresco/repo/policy/traitextender/BehaviourFilterExtension.java, src/main/java/org/alfresco/repo/policy/traitextender/BehaviourFilterTrait.java, src/main/java/org/alfresco/repo/virtual/bundle/VirtualBehaviourFilterExtension.java, src/main/resources/alfresco/smartfolder-context.xml, src/test/java/org/alfresco/AppContextExtraTestSuite.java, src/test/java/org/alfresco/repo/virtual/VirtualizationIntegrationTest.java, src/test/java/org/alfresco/repo/virtual/bundle/VirtualBehaviourFilterExtensionTest.java
The MNT-18895 ticket has highlighted the fact that behaviour filter service did not have an extension when it comes to smart folders.
The issue had to do with the creation of renditions as children of documents, when a document hasn't got any rendition yet, and the rendition is created as a new node from a smart folder, it is only the virtual node that gets its aspect cm:auditable disbaled and not the actual node linked to it.
The cm:auditable is responsible for certain updates of node's properties, in particular the properties cm:modifier and cm:modified.
This merge delivers an extension for behaviour filter service as it is the case already for other services (node, coci, lock, fileFolder..)
* Extension of the BehaviourFilter service for smart folders:
- VirtualBehaviourFilterExtension: …
=> MNT-18895: Extension of Behaviour Filter for Smart Folders  (#791)

src/main/java/org/alfresco/repo/policy/BehaviourFilter.java, src/main/java/org/alfresco/repo/policy/BehaviourFilterImpl.java, src/main/java/org/alfresco/repo/policy/traitextender/BehaviourFilterExtension.java, src/main/java/org/alfresco/repo/policy/traitextender/BehaviourFilterTrait.java, src/main/java/org/alfresco/repo/virtual/bundle/VirtualBehaviourFilterExtension.java, src/main/resources/alfresco/smartfolder-context.xml, src/test/java/org/alfresco/AppContextExtraTestSuite.java, src/test/java/org/alfresco/repo/virtual/VirtualizationIntegrationTest.java, src/test/java/org/alfresco/repo/virtual/bundle/VirtualBehaviourFilterExtensionTest.java
The MNT-18895 ticket has highlighted the fact that behaviour filter service did not have an extension when it comes to smart folders.
The issue had to do with the creation of renditions as children of documents, when a document hasn't got any rendition yet, and the rendition is created as a new node from a smart folder, it is only the virtual node that gets its aspect cm:auditable disbaled and not the actual node linked to it.
The cm:auditable is responsible for certain updates of node's properties, in particular the properties cm:modifier and cm:modified.
This merge delivers an extension for behaviour filter service as it is the case already for other services (node, coci, lock, fileFolder..)
* Extension of the BehaviourFilter service for smart folders:
   - …
=> MNT-18895: Extension of Behaviour Filter for Smart Folders

.travis.yml, pom.xml
This dependency **com.googlecode.mp4parser.isoparser** is not required in [alfresco-repository](https://github.com/Alfresco/alfresco-repository) project and may be source of potential conflicts when used in [alfresco-tika](https://github.com/Alfresco/alfresco-tika) project as describe in the associated ticket [repo-4753](https://issues.alfresco.com/jira/browse/REPO-4753).  
The library has been removed from the pom file and the builds on other projects depending on it have been tested:
* [alfresco-repository](https://travis-ci.com/Alfresco/alfresco-repository/builds/146581358)
* [alfresco-remote-api](https://travis-ci.com/Alfresco/alfresco-remote-api/builds/1466148)
* [alfresco-enterprise-repository](https://travis-ci.com/Alfresco/alfresco-enterprise-repository/builds/146616654)
* …
=> REPO-4753: removing googlecode isoparser dependency

pom.xml
* REPO-4753: remove com.google.mp4parser:isoparser dependency
This dependency is not required in this project and triggers some conflicts in other projects (tika) due to the difference of versions.
(cherry picked from commit 77f08bd1430c6c867edfb0cb388b68e163a4cb54)
=> REPO-4753: removing googlecode isoparser dependency (#796)

src/main/java/org/alfresco/repo/security/permissions/impl/acegi/ACLEntryAfterInvocationProvider.java, src/main/java/org/alfresco/repo/security/permissions/impl/acegi/WeakFilteringResultSet.java, src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryTest.java
* [SEARCH-799] Added WeakFilteringSetResult class. This type of filtering does not concerns permissions and allows to access to the tolal number of elements.
* [SEARCH-799] Added nested filter in. The inner one is for permission filtering and the outer one if for count filtering.
The change concerns the case of optimisePermissionsCheck=true.
* [SEARCH-799] Implemented double filtering when optimizePermission=false. Code refactoring.
* [SEARCH-799] Fix problem in resultSet.length() resulted in org.alfresco.opencmis.CMISTest#testQueryNodesWithCorruptedIndexes test.
* [SEARCH-799] Added unit test for pagination result.
* Syntax fixes.
* Removed import *.
* Set back system user as current user.
* [SEARCH-799] added Javadoc and some useful description in test methods.
* [SEARCH-799] Added …
=> SEARCH-799 filtered results db (#290)

src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
In the context of creating renditions after updating nodes properties, a check of node's existence should be done because of the asynchronousity of renditions.
In the case of mnt-20933, after uploading a new version of the file:
- A new rendition is requested for the working copy because the properties of it have changed, the **request is asynchronous**.
- Then a check-in is processed which **deletes** the working copy noderef.
- Then the code for the new rendition is executed. At this stage, no working copy noderef and the message error _InvalidNodeRefException: Node does not exist_ is thrown.
=> MNT-20933: Does noderef exist before updating rendition

src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
* mnt-20933 Does noderef exist before updating rendition
In the context of creating renditions after updating nodes properties, a check of node's existence must be done because of the asynchronousity of renditions.
(cherry picked from commit 63b607770006c701ac6e2792276b8ef4b53c367e)
=> MNT-20933: Does noderef exist before updating rendition (#865)

src/main/java/org/alfresco/repo/version/VersionServiceImpl.java, src/test/java/org/alfresco/repo/version/BaseVersionStoreTest.java, src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java, src/test/resources/org/alfresco/repo/version/VersionStoreBaseTest_model.xml
- copy marker aspects when creating node's version
- add test marker aspect
- add marker aspect checks on testRevert()
=> MNT-19773 : Marker aspects are not copied to the version store

src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java, src/test/java/org/alfresco/repo/rendition2/RenditionService2Test.java, src/test/resources/alfresco/renditions/test/overrideRendition.json
Relaxed the checks so that it is possible to override rendition definitions. DEBUG is logged in this case.
=> MNT-21398 Unable to override standard rendition definitions

src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceImpl.java
- updated code so the Context set includes the USERNAME field.
- the missing of that field on the context was causing the CMIS lib to trigger a 401
The 401 is triggered at this line, because the username is empty.
The username is empty because it is never set. The created context is an instance of `BrowserCallContextImpl`. No piece of code/logic that is being executed is putting the `USERNAME` in the context.
The context is created as you can see below in `CmisBrowserBindingServlet`.
Immediately after the context is created the request is being dispatched.
After the dispatch, we have access through the Alfresco code to the context.
First in `AlfrescoCmisServiceFactory` which opens the service as per below.
As the `AlfrescoCmisServiceFactory` is no place for modifying the context, I've …
=> REPO-4859 : HTTP_UNAUTHORIZED instead of HTTP_FORBIDDEN for some CMIS apis

src/main/java/org/alfresco/repo/rendition2/LegacyTransformServiceRegistry.java, src/main/java/org/alfresco/repo/rendition2/SwitchingTransformServiceRegistry.java
A V0 API is supplying transformer names. It really should not as the caller should not know the name, but just that the repo can do the transform.
=> ACS-127 Repo Admin - List Mimetypes (Transforms) fails with 500 error

src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java, src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java, src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Replaces PR https://github.com/Alfresco/alfresco-repository/pull/984 
Implements solution provided by @killerboot : 
- When time is exceeded (set on fixedAclMaxTransactionTime), it shall always turn the call async and delegate ACL creation to the job
- Fix the current async behavior to also delegate the current's branch children to the job instead of processing them because they have no children
Aditionally also contains:
- Fix to the FixedACLUpdater job: it was picking up nodes in batches and kept resetting a maxNodeId with the last node of the list so on next iteration it would not pick those up again. Problem is the list is sorted desc, so smallest ID comes last - so the next iteration was picking up everything again except the lowest nodeID from the previous. This caused no error on …
=> MNT-18308 force async acl creation

pom.xml, src/main/java/org/alfresco/repo/content/ContentServiceImpl.java, src/main/java/org/alfresco/service/cmr/repository/ContentService.java, src/main/resources/alfresco/repository.properties, src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
- getDirectAccessUrl now also returns DirectAccessUrl, this will allow us to send null expiresAt and get the ContentStore implementation default value
- changed default value for alfresco.content.directAccessUrl.lifetimeInSec to 300
=> ACS-306: ACS Repository: V1 Rest API for content direct access urls

.travis.yml, pom.xml
- exclude **javax.annotation-api** dependencies (replaced by **jakarta.annotation-api**)
=> MNT-20557: Duplicate inclusion of Java EE Annotations spec API

pom.xml, src/main/java/org/alfresco/repo/content/metadata/TikaAutoMetadataExtracter.java
* Use latest unforked Tika version and exclude the forked version from alfresco-model.
* Bring back the old fix done in https://fisheye.alfresco.com/changelog/alfresco-enterprise?cs=103763
=> REPO-5235: Use unforked tika

src/main/java/org/alfresco/repo/download/CreateDownloadArchiveAction.java, src/main/java/org/alfresco/repo/download/ZipDownloadExporter.java, src/main/resources/alfresco/download-services-context.xml, src/test/java/org/alfresco/repo/download/DownloadServiceIntegrationTest.java
Add dictionaryService to CreateDwonloadArchiveAction
ZipDownloadExporter constructor now required dictionaryService
ZipDownloadExporter#startNode will include into archive all subclasses of node type cm:folder.
Add a custom model and create a custom node in DownloadServiceIntegrationTest, this use case will be tested in DownloadServiceIntegrationTest#createDownload()
=> MNT-21671 : Download as zip REST api does not include custom folders

.travis.yml, src/main/java/org/alfresco/repo/management/subsystems/CryptodocSwitchableApplicationContextFactory.java, src/main/java/org/alfresco/repo/management/subsystems/EncryptedContentStoreChildApplicationContextFactory.java, src/main/java/org/alfresco/repo/management/subsystems/SwitchableApplicationContextFactory.java, src/main/resources/alfresco/content-services-context.xml, src/test/java/org/alfresco/repo/management/subsystems/CryptodocSwitchableApplicationContextFactoryTest.java
* Update `CryptodocSwitchableApplicationContextFactory` to accept switching (via JMX) between existing content store subsystems, not just based on plain bean names.
* Added `EncryptedContentStoreChildApplicationContextFactory` as an extension of `ChildApplicationContextFactory` with support to specify if the content store in the subsystem is encrypted or not.
=> REPO-5094: Allow switching between existing content store subsystems

src/main/resources/alfresco/subsystems/Search/solr4/solr-search-context.xml
This configuration is recommended for upgrading scenarios, where you need to upgrade ACS and to re-index the repository with SOLR 6 while using the system with SOLR 4.
=> SEARCH-2289: Restore the support for SOLR 4 in ACS 6.2+ deployments.

src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java, src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Fix:
- Changed method setFixedAcls on class ADMAccessControlListDAO to continue to propagate through children to apply the correct acl not only when the current child acl matches the shared acl to replace but also when the current child acl matches the new shared acl
Unit Test:
- Refactored the unit test FixedAclUpdaterTest to be able to add in a new test without repeating code: separating the operations that set the permissions from the one that triggers the job into separate methods
- As it was if one test failed, leaving aspects to be processed, the test would run indefinitely (it was programmed to keep running the job while there where nodes with the aspect. Added a verification to stop triggering the job if the number of nodes with the pendingFixAcl did not change between executions. …
=> [MNT-21847] - Aync permissions fail when new nodes are created

src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java, src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Fix:
*Changed method setFixedAcls on class ADMAccessControlListDAO to continue to propagate through children to apply the correct acl not only when the current child acl matches the shared acl to replace but also when the current child acl matches the new shared acl
Unit Test:
*Refactored the unit test FixedAclUpdaterTest to be able to add in a new test without repeating code: separating the operations that set the permissions from the one that triggers the job into separate methods
*As it was if one test failed, leaving aspects to be processed, the test would run indefinitely (it was programmed to keep running the job while there where nodes with the aspect). Added a verification to stop triggering the job if the number of nodes with the pendingFixAcl did not change between executions. …
=> [MNT-21847] - Aync permissions fail when new nodes are created (#1188)

src/main/java/org/alfresco/repo/security/permissions/impl/SimplePermissionReference.java
The piece of code before changes seemed to be designed to provide a thread safe factory for singletons. I didn't find any particular reason for this choice by looking at the usages of SimplePermissionReference in the code. It actually may be sufficient to just create new SimplePermissionReference objects each time.
=> REPO-5339 Improve concurrency of SimplePermissionReference

src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/AlfrescoCreate-RepoTables.sql, src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml, src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/AlfrescoCreate-RepoTables.sql, src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Schema-Reference-ALF.xml, src/main/resources/alfresco/dbscripts/db-schema-context.xml, src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/add-indexes-node-transaction.sql, src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.PostgreSQLDialect/add-indexes-node-transaction.sql, src/main/resources/alfresco/messages/patch-service.properties, src/main/resources/alfresco/patch/patch-services-context.xml, src/main/resources/alfresco/repository.properties
- Added the following indexes on alf_transaction:
idx_alf_txn_ctms_sc, cols (commit_time_ms)
idx_alf_txn_id_ctms, cols (id, commit_time_ms)
- Added the following indexes on alf_node:
idx_alf_node_ver, cols (version)
idx_alf_node_txn, cols (transaction_id)
- Created patch patch.db-V6.3-add-indexes-node-transaction
- Updated version.schema to 14002
- Added system property system.new-node-transaction-indexes.ignored, set
as true by default to not apply the patch automatically
- Created the MySQL update dbscripts to add the new indexes - and also
drop and recreate the pre-existing index idx_alf_txn_ctms on alf_transaction that was
inconsistent with the other DBMS: was indexing only commit_time_ms when
on all other DBMS index idx_alf_txn_ctms was on (commit_time_ms, id)
- Created the Postgres …
=> [MNT-21766]: Significant degradation of performance as file and site count increase

src/main/java/org/alfresco/repo/audit/AuditComponent.java, src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java, src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java, src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java, src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java, src/main/java/org/alfresco/service/cmr/audit/AuditService.java, src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Add CountAuditEntryId select, that provides the total number of items for a specific auditApp
Add getAuditEntriesCountByApp(long appId) in AuditDAO interface and its implementation in AuditDAOImpl
Add getAuditEntriesCountByApp(String applicationName) in AuditComponent interface and its implementation in AuditComponentImpl
Add getAuditEntriesCountByApp(String applicationName) in AuditService interface and its implementation in AuditServiceImpl
=> MNT-21936 : Audit query Rest API does not return the correct totalItems
