Alfresco/alfresco-repository

- pom.xml
- src/main/java/org/alfresco/heartbeat/AuthoritiesDataCollector.java
- src/main/java/org/alfresco/heartbeat/HBBaseDataCollector.java
- src/main/java/org/alfresco/heartbeat/RepositoryDataCollector.java
- src/main/resources/alfresco/application-context-highlevel.xml
- src/main/resources/alfresco/heartbeat/heartbeat-repo-collector-context.xml
- src/test/java/org/alfresco/AllUnitTestsSuite.java
- src/test/java/org/alfresco/heartbeat/AuthoritiesDataCollectorTest.java
- src/test/java/org/alfresco/heartbeat/HeartBeatTest.java
- src/test/java/org/alfresco/heartbeat/RepositoryDataCollectorTest.java
- Add import for heartbeat-enterprise-repo-collector-context.xml
> REPO-2627 Heartbeat: Add data collection to Enterprise code

- src/main/java/org/alfresco/repo/action/executer/ExecuteAllRulesActionExecuter.java
- src/test/java/org/alfresco/repo/action/executer/ExecuteAllRulesActionExecuterTest.java
When executing rules "manually" in Share the request to execute on subfolders was being ignored if the folder was set to "do not inherit rules". The recursion was relying on inheritance of rules, but really the two are separate functionality.
It even turned out that the test `testExecution()` was proving this didn't work: it executed the rules with the recursion option but then tested that the aspect _hadn't_ been added to the items in the subfolder. In the final assertion block:
```
assertFalse(nodeService.hasAspect(doc3, ContentModel.ASPECT_VERSIONABLE));
assertFalse(nodeService.hasAspect(doc3, ContentModel.ASPECT_CLASSIFIABLE));
assertTrue(nodeService.hasAspect(doc3, ContentModel.ASPECT_TITLED));
```
`doc3` should have been affected by all 3 reals due to the recursion option, yet we …
> REPO-3029: MNT-13055 execute rules subfolders

- pom.xml
Jackson is never used in repository code
> REPO-3097 Remove jackson dependency

- src/main/java/org/alfresco/repo/action/executer/MailActionExecuter.java
- src/test/java/org/alfresco/repo/action/executer/AbstractMailActionExecuterTest.java
Set correct values for bcc adress and fix ClassCastException.
> REPO-2957: Community: ALF-21948 Bug with setting CC and BCC fields

- src/main/java/org/alfresco/repo/activities/feed/EmailUserNotifier.java
- src/main/java/org/alfresco/repo/notification/EMailNotificationProvider.java
- src/main/resources/alfresco/subsystems/ActivitiesFeed/default/activities-feed-context.xml
- src/test/java/org/alfresco/repo/activities/feed/FeedNotifierJobTest.java
REPO-2918: ALF-21947 EmailUserNotifier doesn't regard recipient locale preferences
MNT-15287: Activiti Workflow Email subject for workflow are in English while the content is are French
> REPO-2918: ALF-21947 EmailUserNotifier doesn't regard recipient locale preferences

- pom.xml
* Upgrade to latest data sender with updated jackson libs
> REPO-3192: Upgrade alfresco-hb-data-sender version

- pom.xml
- src/main/java/org/alfresco/heartbeat/HBBaseDataCollector.java
- src/main/java/org/alfresco/heartbeat/HBDataCollectorServiceImpl.java
- src/main/java/org/alfresco/service/cmr/repository/HBDataCollectorService.java
- src/test/java/org/alfresco/heartbeat/HBDataCollectorServiceImplTest.java
REPO-3195 Heartbeat Addition of deregister method so that a collector can remove itself once it is done.
> Repo 3195 trial license

- src/main/java/org/alfresco/repo/content/transform/OOoContentTransformerHelper.java
- src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java
- src/main/java/org/alfresco/repo/content/transform/magick/AbstractImageMagickContentTransformerWorker.java
- src/main/java/org/alfresco/repo/content/transform/magick/ImageMagickContentTransformerWorker.java
- src/main/java/org/alfresco/repo/content/transform/pdfrenderer/AlfrescoPdfRendererContentTransformerWorker.java
- src/main/resources/alfresco/repository.properties
- src/main/resources/alfresco/subsystems/OOoJodconverter/default/jodconverter-context.xml
- src/main/resources/alfresco/subsystems/OOoJodconverter/default/jodconverter.properties
- src/main/resources/alfresco/subsystems/thirdparty/default/alfresco-pdf-renderer-transform-context.xml
- src/main/resources/alfresco/subsystems/thirdparty/default/alfresco-pdf-renderer-transform.properties
- src/main/resources/alfresco/subsystems/thirdparty/default/imagemagick-transform-context.xml
REPO-3264 Changes to Jodconverter, alfresco-pdf-renderer & imagamagick to allow transforms to be offloaded to remote transformers (normally docker containers).
> REPO-3264 POC Transformers in Docker

- pom.xml
- set guava library version to 24.0-jre
> REPO-3051: Upgrade Libraries: Guava

- pom.xml
- updated bouncycastle version to 1.59
> REPO-3150: Upgrade Libraries: Bouncycastle

- src/main/resources/alfresco/subsystems/fileServers/default/file-servers.properties
-  Cifs and FTP has been disabled by default
> REPO-3256:EOL Disable CIFS and FTP by default

- src/main/java/org/alfresco/heartbeat/HBDataCollectorServiceImpl.java
Synchronise public methods for manipulating collectors.
> Fix method signatures of HBDataCollectorServiceImpl

- pom.xml
Update the postgres driver to 42.2.1
> REPO-3300: Deployment: 6.0 Base Images Stack Alignment

- src/main/java/org/alfresco/repo/dictionary/DictionaryModelType.java
- src/main/resources/alfresco/policy-context.xml
- src/test/java/org/alfresco/opencmis/BaseCMISTest.java
- src/test/java/org/alfresco/repo/action/executer/SpecialiseTypeActionExecuterTest.java
- src/test/java/org/alfresco/repo/dictionary/DictionaryModelTypeTest.java
- src/test/java/org/alfresco/repo/jscript/ScriptNodeTest.java
- src/test/java/org/alfresco/repo/usage/UserUsageTest.java
Validate location when changing type to "cm:dictionaryModel".
> REPO-3280: Content Model admin security bypass

- src/main/java/org/alfresco/heartbeat/InfoDataCollector.java
- src/main/java/org/alfresco/repo/deployment/DeploymentMethod.java
- src/main/java/org/alfresco/repo/deployment/DeploymentMethodProvider.java
- src/main/java/org/alfresco/repo/deployment/DeploymentMethodProviderImpl.java
- src/main/resources/alfresco/core-services-context.xml
- src/main/resources/alfresco/heartbeat/heartbeat-context.xml
- src/main/resources/alfresco/heartbeat/heartbeat-repo-collector-context.xml
- src/main/resources/alfresco/repository.properties
- src/test/java/org/alfresco/heartbeat/InfoDataCollectorTest.java
- src/test/java/org/alfresco/repo/transfer/NodeCrawlerTest.java
* Add DeploymentMethodProvider which reads the deployment method property
* Set default value for deployment method in repository.properties
* Add deployment method to InfoDataCollector
> REPO-3329: Record deployment method

- src/main/java/org/alfresco/repo/search/impl/solr/SolrQueryHTTPClient.java
- src/main/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClient.java
- src/main/resources/alfresco/subsystems/Search/solr6/solr-search-context.xml
Reverts Alfresco/alfresco-repository#126
> Revert "Fix/search 896"

- src/main/java/org/alfresco/heartbeat/SystemUsageDataCollector.java
- src/main/resources/alfresco/heartbeat/heartbeat-repo-collector-context.xml
- src/test/java/org/alfresco/heartbeat/SystemUsageDataCollectorTest.java
* Group existing memory information together
> REPO-3617: Group memory fields

- pom.xml
Has just bug fixes - but removes stax jar dependency and fixes issues with a number of issues - https://xmlbeans.apache.org/
> xmlbeans 3.0.0

- src/main/java/org/alfresco/repo/thumbnail/ThumbnailDefinition.java
Need ThumbnailDefinition to have a good hashcode to use it as a key in a map.
> REPO-3681 Renditions: Record HeartBeat data from rendition V1 REST API

- src/main/java/org/alfresco/heartbeat/InfoDataCollector.java
- src/main/resources/alfresco/heartbeat/heartbeat-repo-collector-context.xml
- src/test/java/org/alfresco/heartbeat/InfoDataCollectorTest.java
- add the new data points to be collected
- refactor tests to check if the new data is collected
- increment collector version
> REPO-3594: Addition data points for acs.repository.info collector

- src/main/java/org/alfresco/repo/policy/BehaviourFilterImpl.java
- src/test/java/org/alfresco/repo/policy/PolicyComponentTransactionTest.java
Fix and unit tests
Change-Id: I0edc09ec36f4918bcc14a9ed57ad4a099c9a5ae8
> ALF-21992 fix BehaviourFilter check subClass QName

- src/main/java/org/alfresco/heartbeat/SessionsUsageDataCollector.java
- src/main/resources/alfresco/heartbeat/heartbeat-repo-collector-context.xml
- src/test/java/org/alfresco/heartbeat/SessionsUsageDataCollectorTest.java
* Collector gathers data about active tickets
> REPO-3599: Create new acs.repository.usage.sessions data collector

- src/main/java/org/alfresco/repo/policy/EventBehaviour.java
- src/main/java/org/alfresco/repo/rawevents/EventProducer.java
- src/main/java/org/alfresco/repo/rawevents/types/Event.java
- src/main/java/org/alfresco/repo/rawevents/types/EventImpl.java
- src/main/java/org/alfresco/repo/rawevents/types/EventType.java
- src/main/java/org/alfresco/repo/rawevents/types/OnContentUpdatePolicyEvent.java
- src/main/resources/alfresco/messaging-context.xml
- src/main/resources/alfresco/repository.properties
- src/test/java/org/alfresco/ActiveMQ01TestSuite.java
- src/test/java/org/alfresco/repo/rawevents/EventBehaviorTest.java
- added Event behavior and tests
- test that relies on activeMQ to be up is disabled for now
- enabled messaging.subsystem
> REPO-3713: Raw events: onContentUpdate

- src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
Add enterprise routs package to scanned packages for camel messaging
> REPO-3692: Add enterprise routs package to scanned packages

- src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
- src/main/java/org/alfresco/repo/rendition2/LocalTransformServiceRegistry.java
- src/main/java/org/alfresco/repo/rendition2/RenditionDefinition2.java
- src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
- src/main/java/org/alfresco/service/cmr/repository/TransformationOptionLimits.java
- src/main/resources/alfresco/rendition-services2-context.xml
- src/test/java/org/alfresco/repo/rendition2/RenditionDefinitionTest.java
- src/test/resources/log4j.properties
> Repo-3690 Use corrent transformer option names

- src/main/java/org/alfresco/repo/rendition/RenditionDefinitionPersisterImpl.java
- src/main/java/org/alfresco/repo/thumbnail/ThumbnailRegistry.java
- src/main/resources/alfresco/thumbnail-service-context.xml
* throw warning instead of exception for multiple rendition definitions
* db lock the creation of init thumbnail definitions
> REPO-3905 Concurrency problem

- src/main/java/org/alfresco/encryption/EncryptionKeysRegistryImpl.java
I added the RetryingTransaction mechanism on createAttribute. 
I tested following manual steps from MNT-19576 and it's working retrying the createAttribute operation.
> REPO-3930 : JMX errors on "reload" or "reEncrypt" . 

- src/main/java/org/alfresco/repo/events/EventsServiceImpl.java
- small fix to prevent IndexOutOfBoundsException when generating RecordCreatedEvent for records that have been hidden on creation
> APPSREPO-549 : [3.1]CLONE - Error when Declare Record Rule has "Hide" selected

- src/main/java/org/alfresco/opencmis/CMISConnector.java
3 bugs have been fixed in this pull request. For detailed description see below.
**Short description of the fix**
Ensure that the returned token is always updated. This is currently not the case when there are no more items. The next token is set to null in that case, even though there might be (maxItems-1) results. The comments in the code no longer reflected the actual code, which is fixed as well.
This causes bugs where the calling code would get say 900 of a 1000 requested items but a token of null. The only way forward was to get all the items again and ignore duplicates.
**Detailed description of the bugs**
_Issue 1: Returned token from cmis http call to CMISChangeLog returns the wrong changeLogtoken_
When a query is done with Apache Chemistry or manually calling the url it …
> MNT-20139: CmisConnector returns wrong values for changeLogToken and hasMoreItems

- src/main/resources/alfresco/transform-service-config.json
- remove transformations that are not supported by ATS
> ATS-125 : Update transform-service-config.json

- pom.xml
- src/main/java/org/alfresco/repo/security/authentication/identityservice/AuthenticatorAuthzClientFactoryBean.java
- src/main/java/org/alfresco/repo/security/authentication/identityservice/AuthzClientFactoryBean.java
- src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
- src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
- src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication.properties
- src/test/java/org/alfresco/repo/security/SecurityTestSuite.java
- src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java
- src/test/resources/alfresco-global.properties
* Implement new authentication component which authenticates users by obtaining an access token using user's credentials 
* Add keycloak-authz-client dependecy
> Feature/REPO: 3882 Support username password authentication

- src/main/resources/alfresco/repository.properties
- src/main/resources/alfresco/subsystems/Messaging/default/activemq/activemq.xml
- changed from amqp to jms to limit advisory messages
> REPO-4004: 6.1: ActiveMQ has tens of thousands of advisory messages

- src/main/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClient.java
- src/test/java/org/alfresco/AllUnitTestsSuite.java
- src/test/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClientTest.java
Pass filter queries in SQL requests to the Insight Engine.
> RM-6141: RM_support_for_the_Insight_Engine

- src/main/java/org/alfresco/repo/jscript/Search.java
- src/test/java/org/alfresco/repo/jscript/ScriptSearchTest.java
Backporting of changes about MNT-20134 on support/SP/6.56.N branch
> Fix/mnt 20134/6.56.n

- src/main/java/org/alfresco/repo/jscript/Search.java
- src/test/java/org/alfresco/repo/jscript/ScriptSearchTest.java
> Fix/mnt 20134/7.33.n

- src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
- src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
Fix and unit test for https://issues.alfresco.com/jira/browse/ALF-22060
> ALF-22060 Fix Reader on the backing store is obtained twice in CachingContentStore

- pom.xml
- src/main/java/org/alfresco/repo/favourites/PersonFavourite.java
- add title to the PersonFavouriteKey constructor
> REPO-3630/MNT-19696: REST API add order by parameter option to GET favorites

- src/main/java/org/alfresco/filesys/config/SecurityConfigBean.java
- src/main/resources/alfresco/bootstrap-context.xml
- src/main/resources/alfresco/subsystems/fileServers/default/file-servers-context.xml
The property was missed from https://issues.alfresco.com/jira/browse/REPO-3263.
> Remove unused filesystem.domainMappings property

- pom.xml
> Update transient dependencies from TIKA

- pom.xml
> Bring jaxen dependency in repository

- pom.xml
- src/main/resources/alfresco/repository.properties
> REPO-4219 add default alfresco-global properties for CORS

- pom.xml
- https://github.com/Alfresco/gytheio/releases/tag/v0.10
> MM-794: Update Gytheio (Messaging Camel) from 0.9.1 to 0.10

- pom.xml
Bump spring version to 5.1.8.RELEASE
> Merge fix/REPO-4505_update_spring into support/SP/6.56.N

- pom.xml
Bump spring version to 5.1.8.RELEASE
> Merge fix/REPO-4505_upgrade_spring_61N into support/SP/7.33.N

- .travis.yml
- pom.xml
Added cxf-rt-frontend-jaxws dependency to pom.xml
This was causing duplicate asm library errors in support branches.
> REPO-4504 upgrade cxf-rt-transports-http 6.2

- pom.xml
Reverts Alfresco/alfresco-repository#515
> Revert "REPO-4525 / MNT-2075: Multiple camel-jackson vulnerabilities"

- src/main/java/org/alfresco/repo/domain/solr/NodeParametersEntity.java
- src/main/java/org/alfresco/repo/domain/solr/SOLRDAO.java
- src/main/java/org/alfresco/repo/domain/solr/ibatis/SOLRDAOImpl.java
- src/main/java/org/alfresco/repo/search/impl/solr/DbOrIndexSwitchingQueryLanguage.java
- src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
- src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/solr-common-SqlMap.xml
- src/test/java/org/alfresco/repo/domain/solr/SOLRDAOTest.java
- src/test/java/org/alfresco/repo/search/impl/solr/DbOrIndexSwitchingQueryLanguageTest.java
Modified explicit sharding in order to use Int and Long types
> [SEARCH-1746]

- src/main/resources/alfresco/subsystems/Search/noindex/common-search.properties
- src/main/resources/alfresco/subsystems/Search/solr/common-search.properties
- src/main/resources/alfresco/subsystems/Search/solr4/common-search.properties
- src/main/resources/alfresco/subsystems/Search/solr6/common-search.properties
The PR contains a small change which sets the _purgeOnInit_ configuration property to false by default.
> [ SEARCH-1717 ] purgeOnInit flag defaults to false

- src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
- src/main/java/org/alfresco/transform/client/model/config/CombinedConfig.java
- src/main/java/org/alfresco/transform/client/model/config/TransformServiceRegistryImpl.java
- src/main/java/org/alfresco/util/ConfigFileFinder.java
- src/main/java/org/alfresco/util/ConfigScheduler.java
- src/main/resources/alfresco/repository.properties
- read external directories for pipelines and renditions
- bug fix: the renditions schedule was being cleared when the pipeline schedule was cleared
> REPO-4329 Configure Custom renditions

- pom.xml
- TODO: ACS Packaging once we have next corresponding release of alfresco-repository.jar
- https://github.com/Alfresco/acs-packaging/pull/418
> MM-820: Update to Gytheio 0.10.x (=> 0.10.1)

- src/main/java/org/alfresco/repo/content/transform/AbstractLocalTransform.java
- src/main/java/org/alfresco/repo/content/transform/ArchiveContentTransformer.java
- src/main/java/org/alfresco/repo/content/transform/LocalFailoverTransform.java
- src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
- src/main/java/org/alfresco/repo/content/transform/LocalTransformImpl.java
- src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
- src/main/java/org/alfresco/repo/content/transform/PdfBoxContentTransformer.java
- src/main/java/org/alfresco/repo/content/transform/StringExtractingContentTransformer.java
- src/main/java/org/alfresco/repo/content/transform/TikaPoweredContentTransformer.java
- src/main/java/org/alfresco/repo/rendition2/RenditionDefinition2.java
- src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
- src/main/resources/alfresco/transforms/0100-basePipelines.json
- src/main/resources/alfresco/transforms/0150-officeToImageViaPdf.json
- src/test/java/org/alfresco/repo/rendition2/AbstractRenditionTest.java
- src/test/java/org/alfresco/repo/rendition2/LocalRenditionTest.java
- src/test/java/org/alfresco/repo/rendition2/NoneRenditionTest.java
- src/test/java/org/alfresco/transform/client/registry/LocalTransformServiceRegistryConfigTest.java
- src/test/java/org/alfresco/transform/client/registry/TransformServiceRegistryConfigTest.java
- src/test/resources/alfresco/local-transform-service-config-test.json
- src/test/resources/log4j.properties
- Record count of transforms to text
- Allow Local and Service transforms to have their own expected failure lists
> REPO-4452 Add local transformer pipelines

- src/main/java/org/alfresco/repo/node/ContentPropertyRestrictionInterceptor.java
- src/main/resources/alfresco/public-services-context.xml
- src/main/resources/alfresco/repository.properties
- src/test/java/org/alfresco/repo/action/executer/ImporterActionExecuterTest.java
- src/test/java/org/alfresco/repo/content/RoutingContentServiceTest.java
- src/test/java/org/alfresco/repo/content/cleanup/ContentStoreCleanerTest.java
- src/test/java/org/alfresco/repo/forum/CommentsTest.java
- src/test/java/org/alfresco/repo/node/BaseNodeServiceTest.java
- src/test/java/org/alfresco/repo/node/NodeServiceTest.java
For more details about offending services please see [ #565](https://github.com/Alfresco/alfresco-repository/pull/565)
> REPO-4619 Add content property restrictions via interceptor 6.1.N

- src/main/java/org/alfresco/repo/node/ContentPropertyRestrictionInterceptor.java
- src/main/resources/alfresco/public-services-context.xml
- src/main/resources/alfresco/repository.properties
- src/test/java/org/alfresco/repo/action/executer/ImporterActionExecuterTest.java
- src/test/java/org/alfresco/repo/content/RoutingContentServiceTest.java
- src/test/java/org/alfresco/repo/content/cleanup/ContentStoreCleanerTest.java
- src/test/java/org/alfresco/repo/forum/CommentsTest.java
- src/test/java/org/alfresco/repo/node/BaseNodeServiceTest.java
- src/test/java/org/alfresco/repo/node/NodeServiceTest.java
For more details about offending services please see [ #565](https://github.com/Alfresco/alfresco-repository/pull/565)
> REPO-4619 Add content property restrictions via interceptor 6.0.N

- src/main/resources/alfresco/transforms/0100-basePipelines.json
* Text based pipelines for dita formats
> REPO-4452: Add pipeline for text based mimetypes

- pom.xml
- src/main/resources/alfresco/heartbeat/heartbeat-context.xml
- src/main/resources/alfresco/repository.properties
* Remove HB sender cron expression and test mode properties
> REPO-4689: Update HB sender and remove unused properties

- .travis.yml
- pom.xml
- src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
- src/main/java/org/alfresco/repo/jscript/SandboxNativeJavaObject.java
- src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Changed the initialization of secure scope.
> MNT-21009 :  Sandboxed  arbitrary Code Execution

- pom.xml
- src/main/java/org/alfresco/repo/content/transform/TransformerDebug.java
- src/main/java/org/alfresco/repo/rendition2/LegacySynchronousTransformClient.java
- src/main/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClient.java
- src/main/java/org/alfresco/repo/rendition2/SwitchingSynchronousTransformClient.java
- src/main/java/org/alfresco/repo/rendition2/SynchronousTransformClient.java
- src/test/java/org/alfresco/repo/thumbnail/ThumbnailServiceImplTest.java
- Improve TransformerDebug for isSupported call
> REPO-4791 Use Local transforms where Legacy transforms are called.

- pom.xml
- spring security 5.2.1 and spring framework 5.2.2
> REPO-4751: Upgrade to Spring 5.2

- src/main/resources/alfresco/messages/templates-messages.properties
REPO-4314 Service Pack: MNT-20415 HTML tags displayed on notification email for user added to site
> REPO-4314 Service Pack: MNT-20415 HTML tags displayed on notification email for user added to site

- pom.xml
Bump data model to 8.75
Bump core to 8.12
Bump jackson to 2.10.2
> REPO-4917 : Bump dependencies

- pom.xml
- updated transform model version
> ATS-654 :  Release Transform Model 1.0.2.8 component library

- src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
Unites two cycles of getChildAssocs and getParentAssocs calls.
> SEARCH-2051 Performance of metadata tracking

- src/main/java/org/alfresco/service/license/LicenseDescriptor.java
Reverts Alfresco/alfresco-repository#793
> Revert "REPO-4709 remove cloud sync"

- src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBResultSet.java
- src/test/java/org/alfresco/opencmis/CMISTest.java
Unguarded access to a Pair value retriev using nodeDao.getNodePair.
> MNT-20932: Unguarded access to a Pair value retrieved using nodeDao.getNodePair method which can return null

- src/test/java/org/alfresco/opencmis/CMISTest.java
This test was written for Lucene systems, and no longer applies to Solr systems.
This change also deletes the unused logger and factory classes.
> MNT-20822 Delete CMISTest.testQueryNodesWithCorruptedIndexes.

- src/test/java/org/alfresco/opencmis/CMISTest.java
This test was written for Lucene systems, and no longer applies to Solr systems.
(cherry picked from commit 2127724306637f1e89ffd6c6204c663f18927a44)
> MNT-20822 Delete CMISTest.testQueryNodesWithCorruptedIndexes. (#849)

- src/main/java/org/alfresco/repo/search/impl/solr/ExplicitSolrStoreMappingWrapper.java
- src/test/java/org/alfresco/repo/search/impl/solr/SolrStoreMappingWrapperTest.java
Added shard protocol in solr request for manual sharding.
Changed unit tests
> [SEARCH-2122]

- pom.xml
- src/main/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerImpl.java
- src/test/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerTest.java
> MNT-21472 : Space in Windows installation path cause FileNotFound

- pom.xml
- src/main/resources/alfresco/subsystems/Search/solr/solr-search-context.xml
- src/main/resources/alfresco/subsystems/Search/solr/solr-search.properties
- src/main/resources/alfresco/subsystems/Search/solr4/solr-search-context.xml
- src/main/resources/alfresco/subsystems/Search/solr4/solr-search.properties
- src/main/resources/alfresco/subsystems/Search/solr6/solr-search-context.xml
- src/main/resources/alfresco/subsystems/Search/solr6/solr-search.properties
- add HttpClientFactory timeout properties in the SOLR contexts
> MNT-19887: Non-responsive SOLR address breaks admin console pages

- src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
- src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
- src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
- src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
- add create-delete node in the same transaction
- add create-update node in the same transaction
- add create multiple nodes in the same transaction
- validate properties before deleting a node
> REPO-5101-Update Repo Event Integration Tests

- pom.xml
- src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
- src/main/java/org/alfresco/transform/client/registry/TransformServiceRegistryImpl.java
- src/main/resources/alfresco/content-services-context.xml
- src/main/resources/alfresco/rendition-services2-context.xml
Suppresses reading of new config if the system is shutting down.
> REPO-5110 readConfigAndReplace NPE on shutdown

- src/main/resources/alfresco/repository.properties
- src/test/resources/alfresco-global.properties
The defaults are now:
encryption.keyAlgorithm=AES
encryption.cipherAlgorithm=AES/CBC/PKCS5Padding
encryption.keystore.type=pkcs12
encryption.keystore.backup.type=pkcs12
> SEARCH-1915 Update default keystore properties

- pom.xml
- src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
- src/main/java/org/alfresco/service/cmr/repository/ContentService.java
- src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
> ACS-304 : ACS Repository: support for content direct access urls

- .travis.yml
Update of alfresco-transform-core from 2.2.1 to 2.2.2
> ATS-753 bump T- engines to 2.2.2

- src/main/resources/alfresco/subsystems/Search/solr6/common-search.properties
added new configuration parameter in shardRegistry
> [SEARCH-2279]

- .travis.yml
(cherry picked from commit 8bf1a0752a9fb57b61634140846f6c272859546b)
> ATS-791: Update to T-Engines 2.3.1 (#1072)

- .travis.yml
Start update of PostgreSQL references from 11.4 to 11.7 with interim step 11.6
> Update PostgreSQL 11.4 to 11.6

- .travis.yml
* Update PostgreSQL 11.4 to 11.6, interim step
* Update PostgreSQL from 11.6 to 11.7. We got a green build on 11.6.
* We got green build on both 11.6 and 11.7
(cherry picked from commit 35715e40f4bd0e18fcd90f49da8aaafc26865d39)
> Update PostgreSQL 11.4 to 11.7 (#1078)

- src/main/resources/alfresco/repository.properties
- src/test/resources/alfresco-global.properties
> MNT-21731 SEARCH-1915: Update default keystore properties

- src/main/java/org/alfresco/repo/security/sync/ldap/LDAPUserRegistry.java
- src/test/java/org/alfresco/repo/security/sync/LDAPUserRegistryTest.java
- Catch reported exceptions to filter ldap sync aborts
> MNT-21614: LDAP sync communication error leads to group members deletion

- src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
- src/test/java/org/alfresco/repo/solr/SOLRTrackingComponentUnitTest.java
(cherry picked from commit 2fea6c9484def402e2bfd7c3717071ff8df69c01)
> SEARCH-2450 Don't expose properties from solr endpoint if the model says not to index them. (#1228)

- src/main/java/org/alfresco/opencmis/TransactionAwareHolder.java
> Fix/MNT-21800 CMIS Web Service Check Out returns error

- .travis.yml
- pom.xml
> MNT-21871 : [Security] Multiple jackson-databind vulnerabilities
